# Generated by Django 4.2.13 on 2024-06-04 22:05

import carSearch_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carSearch_app', '0002_carlist_chassisnumber_carlist_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showroomlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[carSearch_app.models.alphanumeric]),
        ),
    ]
