# Generated by Django 4.2.13 on 2024-06-04 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carSearch_app', '0003_showroomlist_alter_carlist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='showrooms', to='carSearch_app.showroomlist'),
        ),
    ]
