# Generated by Django 4.2.13 on 2024-06-04 22:59

import carSearch_app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carSearch_app', '0004_carlist_showroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='chassisnumber',
            field=models.CharField(max_length=50, null=True, validators=[carSearch_app.models.alphanumeric]),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comments', models.CharField(max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='carSearch_app.carlist')),
            ],
        ),
    ]
